import { CreatorCategory, DeliverableType, PlatformType } from "../types";

export const CATEGORIES: CreatorCategory[] = [
  'Technology & AI',
  'Design & Creative',
  'Fashion & Style',
  'Beauty & Skincare',
  'Fitness & Wellness',
  'Finance & Business',
  'Gaming & Esports',
  'Lifestyle & Travel',
  'Food & Culinary',
  'Education & Science',
];

export const PLATFORMS: { id: PlatformType; name: string; color: string; icon: string }[] = [
  { id: 'instagram', name: 'Instagram', color: '#E1306C', icon: 'Instagram' },
  { id: 'youtube', name: 'YouTube', color: '#FF0000', icon: 'Youtube' },
  { id: 'tiktok', name: 'TikTok', color: '#00F2FE', icon: 'Video' },
  { id: 'x', name: 'X / Twitter', color: '#000000', icon: 'Twitter' },
  { id: 'linkedin', name: 'LinkedIn', color: '#0A66C2', icon: 'Linkedin' },
  { id: 'threads', name: 'Threads', color: '#000000', icon: 'AtSign' },
];

export const DELIVERABLE_TYPES: DeliverableType[] = [
  'Instagram Reel',
  'Instagram Story Set (3x)',
  'Instagram Dedicated Post',
  'YouTube Dedicated Video',
  'YouTube 60s Integration',
  'YouTube Short',
  'TikTok Video',
  'UGC Video Ad',
  'X (Twitter) Thread',
  'Keynote / Event Appearance',
];

export const CREATOR_TIERS = [
  { label: 'Rising (10K - 50K)', value: 'Rising', min: 10000, max: 50000, avgRate: '$400 - $1,500' },
  { label: 'Established (50K - 250K)', value: 'Established', min: 50000, max: 250000, avgRate: '$1,500 - $4,000' },
  { label: 'Elite (250K - 1M)', value: 'Elite', min: 250000, max: 1000000, avgRate: '$4,000 - $15,000' },
  { label: 'Premium (1M+)', value: 'Premium', min: 1000000, max: 100000000, avgRate: '$15,000+' },
];

import { SubscriptionPlan, SubscriptionPlanId } from "../types";

export const CREATOR_PLANS: Record<string, SubscriptionPlan> = {
  creator_starter: {
    id: "creator_starter",
    name: "Creator Starter",
    badge: "FREE FOREVER",
    role: "creator",
    monthlyPrice: 0,
    annualPrice: 0,
    description: "For emerging creators building an audited media kit and pitching verified brands.",
    highlight: false,
    features: {
      mediaKit: true,
      maxApplicationsPerMonth: 5,
      instantPayouts: false,
      advancedAnalytics: false,
      aiPitchGenerator: false,
      verifiedBadge: false,
      priorityDiscovery: false,
      multiCreatorManagement: false,
      customDomain: false,
      maxActiveCampaigns: 0,
      crmPipeline: false,
      aiCreatorMatching: false,
      creatorShortlists: false,
      maxTeamSeats: 0,
      advancedRoiTelemetry: false,
      contractCompliance: false,
      dedicatedAccountManager: false,
      apiAccess: false,
    },
    featureBullets: [
      "Audited 1-click Media Kit",
      "Apply to up to 5 campaigns / month",
      "100% Escrow payout guarantee",
      "4K Video review player",
      "Standard engagement metrics",
    ],
    limitations: [
      "5 campaign applications limit per month",
      "Standard 7-day milestone payout release",
      "Audience retention curves locked",
      "AI pitch generator locked",
    ],
  },
  creator_pro: {
    id: "creator_pro",
    name: "Creator Pro",
    badge: "MOST POPULAR",
    role: "creator",
    monthlyPrice: 29,
    annualPrice: 24,
    description: "For full-time creators scaling commercial sponsorships and securing higher brand rates.",
    highlight: true,
    features: {
      mediaKit: true,
      maxApplicationsPerMonth: -1, // Unlimited
      instantPayouts: true,
      advancedAnalytics: true,
      aiPitchGenerator: true,
      verifiedBadge: true,
      priorityDiscovery: true,
      multiCreatorManagement: false,
      customDomain: false,
      maxActiveCampaigns: 0,
      crmPipeline: false,
      aiCreatorMatching: false,
      creatorShortlists: false,
      maxTeamSeats: 0,
      advancedRoiTelemetry: false,
      contractCompliance: false,
      dedicatedAccountManager: false,
      apiAccess: false,
    },
    featureBullets: [
      "Unlimited campaign applications",
      "Instant 2-hour escrow payout release",
      "Deep audience analytics & retention intel",
      "AI Pitch Generator & match booster",
      "Gold Pro Verified Creator badge",
      "Priority recommendation to brands in search",
    ],
  },
  creator_enterprise: {
    id: "creator_enterprise",
    name: "Creator Studio & Collective",
    badge: "AGENCY & TEAMS",
    role: "creator",
    monthlyPrice: 99,
    annualPrice: 79,
    description: "For creator collectives, talent managers, and multi-channel media production houses.",
    highlight: false,
    features: {
      mediaKit: true,
      maxApplicationsPerMonth: -1,
      instantPayouts: true,
      advancedAnalytics: true,
      aiPitchGenerator: true,
      verifiedBadge: true,
      priorityDiscovery: true,
      multiCreatorManagement: true,
      customDomain: true,
      maxActiveCampaigns: 0,
      crmPipeline: false,
      aiCreatorMatching: false,
      creatorShortlists: false,
      maxTeamSeats: 0,
      advancedRoiTelemetry: false,
      contractCompliance: false,
      dedicatedAccountManager: true,
      apiAccess: true,
    },
    featureBullets: [
      "Everything in Creator Pro",
      "Manage up to 10 creator profiles",
      "Custom escrow split payouts",
      "White-labeled Media Kit & custom domain",
      "Automated contract & 1099 compliance",
      "Dedicated Talent Concierge & VIP SLA",
    ],
  },
};

export const BRAND_PLANS: Record<string, SubscriptionPlan> = {
  brand_starter: {
    id: "brand_starter",
    name: "Brand Starter",
    badge: "EXPLORATION",
    role: "brand",
    monthlyPrice: 49,
    annualPrice: 39,
    description: "For early-stage startups and small businesses running pilot influencer campaigns.",
    highlight: false,
    features: {
      mediaKit: false,
      maxApplicationsPerMonth: 0,
      instantPayouts: false,
      advancedAnalytics: false,
      aiPitchGenerator: false,
      verifiedBadge: false,
      priorityDiscovery: false,
      multiCreatorManagement: false,
      customDomain: false,
      maxActiveCampaigns: 2,
      crmPipeline: false,
      aiCreatorMatching: false,
      creatorShortlists: true,
      maxTeamSeats: 1,
      advancedRoiTelemetry: false,
      contractCompliance: false,
      dedicatedAccountManager: false,
      apiAccess: false,
    },
    featureBullets: [
      "Up to 2 active campaign briefs",
      "Creator discovery directory & filters",
      "100% Escrow deposit protection",
      "4K Video review & timecoded feedback",
      "Single seat workspace",
    ],
    limitations: [
      "2 active campaigns maximum",
      "Creator CRM pipeline locked",
      "AI matching scores locked",
      "Advanced ROI telemetry locked",
    ],
  },
  brand_growth: {
    id: "brand_growth",
    name: "Brand Growth",
    badge: "SCALE & ROI",
    role: "brand",
    monthlyPrice: 199,
    annualPrice: 159,
    description: "For fast-growing marketing teams running continuous multi-creator pipelines.",
    highlight: true,
    features: {
      mediaKit: false,
      maxApplicationsPerMonth: 0,
      instantPayouts: false,
      advancedAnalytics: false,
      aiPitchGenerator: false,
      verifiedBadge: false,
      priorityDiscovery: false,
      multiCreatorManagement: false,
      customDomain: false,
      maxActiveCampaigns: 10,
      crmPipeline: true,
      aiCreatorMatching: true,
      creatorShortlists: true,
      maxTeamSeats: 5,
      advancedRoiTelemetry: true,
      contractCompliance: true,
      dedicatedAccountManager: false,
      apiAccess: false,
    },
    featureBullets: [
      "Up to 10 active campaign briefs",
      "Full Creator CRM pipeline & private notes",
      "AI creator matching & suitability scoring",
      "Up to 5 team workspace seats",
      "Advanced ROI telemetry & conversion curves",
      "Automated contracts & tax compliance",
    ],
  },
  brand_enterprise: {
    id: "brand_enterprise",
    name: "Brand Enterprise",
    badge: "GLOBAL ENTERPRISE",
    role: "brand",
    monthlyPrice: 599,
    annualPrice: 499,
    description: "For high-volume brands and marketing agencies orchestrating large-scale creator rosters.",
    highlight: false,
    features: {
      mediaKit: false,
      maxApplicationsPerMonth: 0,
      instantPayouts: false,
      advancedAnalytics: false,
      aiPitchGenerator: false,
      verifiedBadge: false,
      priorityDiscovery: false,
      multiCreatorManagement: false,
      customDomain: false,
      maxActiveCampaigns: -1, // Unlimited
      crmPipeline: true,
      aiCreatorMatching: true,
      creatorShortlists: true,
      maxTeamSeats: -1, // Unlimited
      advancedRoiTelemetry: true,
      contractCompliance: true,
      dedicatedAccountManager: true,
      apiAccess: true,
    },
    featureBullets: [
      "Unlimited active campaigns & creators",
      "Unlimited team workspace seats",
      "Dedicated Account Director & Escrow Concierge",
      "Custom API & Webhook integrations",
      "Custom Master Services Agreements & Legal Addendums",
      "Custom SLA & 24/7 Priority Support",
    ],
  },
};

export const ALL_PLANS: Record<SubscriptionPlanId, SubscriptionPlan> = {
  ...CREATOR_PLANS,
  ...BRAND_PLANS,
} as Record<SubscriptionPlanId, SubscriptionPlan>;

