import type { CreatorCategory, DeliverableType, PlatformType } from "../types";

export const CATEGORIES: CreatorCategory[] = [
  'Technology & AI',
  'Design & Creative',
  'Fashion & Style',
  'Beauty & Skincare',
  'Fitness & Wellness',
  'Finance & Business',
  'Gaming & Esports',
  'Lifestyle & Travel',
  'Food & Culinary',
  'Education & Science',
];

export const PLATFORMS: { id: PlatformType; name: string; color: string; icon: string }[] = [
  { id: 'instagram', name: 'Instagram', color: '#E1306C', icon: 'Instagram' },
  { id: 'youtube', name: 'YouTube', color: '#FF0000', icon: 'Youtube' },
  { id: 'tiktok', name: 'TikTok', color: '#00F2FE', icon: 'Video' },
  { id: 'x', name: 'X / Twitter', color: '#000000', icon: 'Twitter' },
  { id: 'linkedin', name: 'LinkedIn', color: '#0A66C2', icon: 'Linkedin' },
  { id: 'threads', name: 'Threads', color: '#000000', icon: 'AtSign' },
];

export const DELIVERABLE_TYPES: DeliverableType[] = [
  'Instagram Reel',
  'Instagram Story Set (3x)',
  'Instagram Dedicated Post',
  'YouTube Dedicated Video',
  'YouTube 60s Integration',
  'YouTube Short',
  'TikTok Video',
  'UGC Video Ad',
  'X (Twitter) Thread',
  'Keynote / Event Appearance',
];

export const CREATOR_TIERS = [
  { label: 'Rising (10K - 50K)', value: 'Rising', min: 10000, max: 50000, avgRate: '$400 - $1,500' },
  { label: 'Established (50K - 250K)', value: 'Established', min: 50000, max: 250000, avgRate: '$1,500 - $4,000' },
  { label: 'Elite (250K - 1M)', value: 'Elite', min: 250000, max: 1000000, avgRate: '$4,000 - $15,000' },
  { label: 'Premium (1M+)', value: 'Premium', min: 1000000, max: 100000000, avgRate: '$15,000+' },
];

import { SubscriptionPlan, SubscriptionPlanId } from "../types/index";

export const CREATOR_PLANS: Record<string, SubscriptionPlan> = {
  creator_starter: {
    id: "creator_starter",
    name: "Creator Starter",
    badge: "FREE FOREVER",
    role: "creator",
    monthlyPrice: 0,
    annualPrice: 0,
    description: "For creators building their media kit and applying to their first brand deals.",
    highlight: false,
    features: {
      mediaKit: true,
      maxApplicationsPerMonth: 5,
      instantPayouts: false,
      advancedAnalytics: false,
      aiPitchGenerator: false,
      verifiedBadge: false,
      priorityDiscovery: false,
      multiCreatorManagement: false,
      customDomain: false,
      maxActiveCampaigns: 0,
      crmPipeline: false,
      aiCreatorMatching: false,
      creatorShortlists: false,
      maxTeamSeats: 0,
      advancedRoiTelemetry: false,
      contractCompliance: false,
      dedicatedAccountManager: false,
      apiAccess: false,
    },
    featureBullets: [
      "Ready-to-share Media Kit",
      "Apply to up to 5 brand campaigns / month",
      "Guaranteed payment on approved work",
      "Draft preview & feedback workspace",
      "Audience overview metrics",
    ],
    limitations: [
      "5 campaign applications per month",
      "Standard payout timeline (up to 7 days)",
      "Detailed audience graphs locked",
      "AI pitch helper locked",
    ],
  },
  creator_pro: {
    id: "creator_pro",
    name: "Creator Pro",
    badge: "MOST POPULAR",
    role: "creator",
    monthlyPrice: 29,
    annualPrice: 24,
    description: "For full-time creators pitching more brands, closing deals faster, and getting paid quickly.",
    highlight: true,
    features: {
      mediaKit: true,
      maxApplicationsPerMonth: -1, // Unlimited
      instantPayouts: true,
      advancedAnalytics: true,
      aiPitchGenerator: true,
      verifiedBadge: true,
      priorityDiscovery: true,
      multiCreatorManagement: false,
      customDomain: false,
      maxActiveCampaigns: 0,
      crmPipeline: false,
      aiCreatorMatching: false,
      creatorShortlists: false,
      maxTeamSeats: 0,
      advancedRoiTelemetry: false,
      contractCompliance: false,
      dedicatedAccountManager: false,
      apiAccess: false,
    },
    featureBullets: [
      "Unlimited campaign applications",
      "Fast 2-hour payouts once approved",
      "Deep audience demographics & engagement insights",
      "AI Pitch Helper to write better proposals",
      "Gold Verified Creator badge",
      "Featured placement in creator search",
    ],
  },
  creator_enterprise: {
    id: "creator_enterprise",
    name: "Creator Studio & Collective",
    badge: "TEAMS & MANAGERS",
    role: "creator",
    monthlyPrice: 99,
    annualPrice: 79,
    description: "For creator teams, talent managers, and production studios managing multiple rosters.",
    highlight: false,
    features: {
      mediaKit: true,
      maxApplicationsPerMonth: -1,
      instantPayouts: true,
      advancedAnalytics: true,
      aiPitchGenerator: true,
      verifiedBadge: true,
      priorityDiscovery: true,
      multiCreatorManagement: true,
      customDomain: true,
      maxActiveCampaigns: 0,
      crmPipeline: false,
      aiCreatorMatching: false,
      creatorShortlists: false,
      maxTeamSeats: 0,
      advancedRoiTelemetry: false,
      contractCompliance: false,
      dedicatedAccountManager: true,
      apiAccess: true,
    },
    featureBullets: [
      "Everything in Creator Pro",
      "Manage up to 10 creator profiles",
      "Flexible split payouts for teams",
      "Custom domain for your media kit",
      "Ready-to-use agreements & tax documents",
      "Dedicated manager & priority support",
    ],
  },
};

export const BRAND_PLANS: Record<string, SubscriptionPlan> = {
  brand_starter: {
    id: "brand_starter",
    name: "Brand Starter",
    badge: "GETTING STARTED",
    role: "brand",
    monthlyPrice: 49,
    annualPrice: 39,
    description: "For startups and small teams running their first creator campaigns.",
    highlight: false,
    features: {
      mediaKit: false,
      maxApplicationsPerMonth: 0,
      instantPayouts: false,
      advancedAnalytics: false,
      aiPitchGenerator: false,
      verifiedBadge: false,
      priorityDiscovery: false,
      multiCreatorManagement: false,
      customDomain: false,
      maxActiveCampaigns: 2,
      crmPipeline: false,
      aiCreatorMatching: false,
      creatorShortlists: true,
      maxTeamSeats: 1,
      advancedRoiTelemetry: false,
      contractCompliance: false,
      dedicatedAccountManager: false,
      apiAccess: false,
    },
    featureBullets: [
      "Up to 2 active campaigns at once",
      "Search and filter verified creators",
      "Safe payments held until you approve",
      "Preview video drafts and leave feedback",
      "Single-user workspace",
    ],
    limitations: [
      "2 active campaigns at a time",
      "Saved contact notes locked",
      "Creator match scores locked",
      "In-depth performance analytics locked",
    ],
  },
  brand_growth: {
    id: "brand_growth",
    name: "Brand Growth",
    badge: "FOR GROWING BRANDS",
    role: "brand",
    monthlyPrice: 199,
    annualPrice: 159,
    description: "For marketing teams collaborating with multiple creators each month.",
    highlight: true,
    features: {
      mediaKit: false,
      maxApplicationsPerMonth: 0,
      instantPayouts: false,
      advancedAnalytics: false,
      aiPitchGenerator: false,
      verifiedBadge: false,
      priorityDiscovery: false,
      multiCreatorManagement: false,
      customDomain: false,
      maxActiveCampaigns: 10,
      crmPipeline: true,
      aiCreatorMatching: true,
      creatorShortlists: true,
      maxTeamSeats: 5,
      advancedRoiTelemetry: true,
      contractCompliance: true,
      dedicatedAccountManager: false,
      apiAccess: false,
    },
    featureBullets: [
      "Up to 10 active campaigns at once",
      "Save creator contacts with private team notes",
      "Smart creator recommendations for your brief",
      "Up to 5 team member accounts",
      "Detailed campaign results & click tracking",
      "Ready-to-use contracts & tax invoices",
    ],
  },
  brand_enterprise: {
    id: "brand_enterprise",
    name: "Brand Enterprise",
    badge: "LARGE TEAMS & AGENCIES",
    role: "brand",
    monthlyPrice: 599,
    annualPrice: 499,
    description: "For agencies and large brands managing ongoing creator partnerships at scale.",
    highlight: false,
    features: {
      mediaKit: false,
      maxApplicationsPerMonth: 0,
      instantPayouts: false,
      advancedAnalytics: false,
      aiPitchGenerator: false,
      verifiedBadge: false,
      priorityDiscovery: false,
      multiCreatorManagement: false,
      customDomain: false,
      maxActiveCampaigns: -1, // Unlimited
      crmPipeline: true,
      aiCreatorMatching: true,
      creatorShortlists: true,
      maxTeamSeats: -1, // Unlimited
      advancedRoiTelemetry: true,
      contractCompliance: true,
      dedicatedAccountManager: true,
      apiAccess: true,
    },
    featureBullets: [
      "Unlimited active campaigns & creators",
      "Unlimited team member accounts",
      "Dedicated account manager & payment specialist",
      "Custom integrations & webhooks",
      "Custom agreements & terms of service",
      "Priority phone, email & chat support",
    ],
  },
};

export const ALL_PLANS: Record<SubscriptionPlanId, SubscriptionPlan> = {
  ...CREATOR_PLANS,
  ...BRAND_PLANS,
} as Record<SubscriptionPlanId, SubscriptionPlan>;

export const GLOBAL_REGIONS = [
  { id: "all", name: "Worldwide (All Regions)" },
  { id: "north_america", name: "North America (US, CA)" },
  { id: "europe", name: "Europe (UK, EU, CH)" },
  { id: "asia_pacific", name: "Asia-Pacific (IN, SG, JP, AU)" },
  { id: "middle_east", name: "Middle East & Africa (UAE, SA, ZA)" },
  { id: "latin_america", name: "Latin America (BR, MX, AR)" },
] as const;

export const GLOBAL_HUBS = [
  "Worldwide",
  "San Francisco",
  "New York",
  "Los Angeles",
  "London",
  "Berlin",
  "Paris",
  "Amsterdam",
  "Mumbai",
  "Bangalore",
  "Singapore",
  "Tokyo",
  "Seoul",
  "Sydney",
  "Dubai",
  "Toronto",
  "São Paulo",
] as const;

export const GLOBAL_PAYMENT_METHODS = [
  { id: "razorpay_checkout", name: "Razorpay Standard Checkout (UPI, Cards, NetBanking)", icon: "ShieldCheck" },
  { id: "razorpay_me", name: "Razorpay.me Direct Handle (https://razorpay.me/@abeycollab)", icon: "ExternalLink" },
  { id: "paypal_global", name: "PayPal Global", icon: "Wallet" },
  { id: "wise_transfer", name: "Wise Cross-Border Transfer", icon: "ArrowRightLeft" },
  { id: "swift_wire", name: "International SWIFT Wire", icon: "Landmark" },
] as const;


