import { DatabaseState, UserEntity } from "./schema";
import { hashPassword } from "../auth/crypto";
import { MOCK_CREATORS } from "@/mock/creators.mock";
import { MOCK_BRANDS } from "@/mock/brands.mock";
import { MOCK_CAMPAIGNS } from "@/mock/campaigns.mock";
import { MOCK_COLLABORATIONS } from "@/mock/collaborations.mock";
import { MOCK_CONVERSATIONS, MOCK_MESSAGES } from "@/mock/messages.mock";
import { ALL_PLANS } from "@/core/constants";
import { SubscriptionEntity } from "@/core/types";

export function getInitialSeedDatabase(): DatabaseState {
  const defaultPasswordHash = hashPassword("password123");
  const adminPasswordHash = hashPassword("admin123");

  const initialUsers: UserEntity[] = [
    {
      id: "user-c1",
      name: "Elena Rostova",
      email: "elena@example.com",
      passwordHash: defaultPasswordHash,
      role: "creator",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
      verified: true,
      createdAt: "2025-01-15T00:00:00Z",
      updatedAt: "2026-08-28T00:00:00Z",
    },
    {
      id: "user-c2",
      name: "Marcus Vance",
      email: "marcus@example.com",
      passwordHash: defaultPasswordHash,
      role: "creator",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80",
      verified: true,
      createdAt: "2025-02-10T00:00:00Z",
      updatedAt: "2026-08-28T00:00:00Z",
    },
    {
      id: "user-c-starter",
      name: "Sam Starter",
      email: "starter.creator@collably.io",
      passwordHash: defaultPasswordHash,
      role: "creator",
      avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop&q=80",
      verified: true,
      createdAt: "2026-01-10T00:00:00Z",
      updatedAt: "2026-08-28T00:00:00Z",
    },
    {
      id: "user-c-pro",
      name: "Petra Pro",
      email: "pro.creator@collably.io",
      passwordHash: defaultPasswordHash,
      role: "creator",
      avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80",
      verified: true,
      createdAt: "2026-01-15T00:00:00Z",
      updatedAt: "2026-08-28T00:00:00Z",
    },
    {
      id: "user-c-ent",
      name: "Evan Collective",
      email: "enterprise.creator@collably.io",
      passwordHash: defaultPasswordHash,
      role: "creator",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80",
      verified: true,
      createdAt: "2026-02-01T00:00:00Z",
      updatedAt: "2026-08-28T00:00:00Z",
    },
    {
      id: "user-b1",
      name: "Linear Dynamics",
      email: "sarah@linear.app",
      passwordHash: defaultPasswordHash,
      role: "brand",
      avatarUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80",
      verified: true,
      createdAt: "2024-11-20T00:00:00Z",
      updatedAt: "2026-08-28T00:00:00Z",
    },
    {
      id: "user-b-starter",
      name: "Novice Brand Co",
      email: "starter.brand@collably.io",
      passwordHash: defaultPasswordHash,
      role: "brand",
      avatarUrl: "https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=200&auto=format&fit=crop&q=80",
      verified: true,
      createdAt: "2026-01-20T00:00:00Z",
      updatedAt: "2026-08-28T00:00:00Z",
    },
    {
      id: "user-b-growth",
      name: "Apex Growth Labs",
      email: "growth.brand@collably.io",
      passwordHash: defaultPasswordHash,
      role: "brand",
      avatarUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=200&auto=format&fit=crop&q=80",
      verified: true,
      createdAt: "2026-02-10T00:00:00Z",
      updatedAt: "2026-08-28T00:00:00Z",
    },
    {
      id: "user-b-ent",
      name: "OmniCorp Global",
      email: "enterprise.brand@collably.io",
      passwordHash: defaultPasswordHash,
      role: "brand",
      avatarUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&auto=format&fit=crop&q=80",
      verified: true,
      createdAt: "2026-01-01T00:00:00Z",
      updatedAt: "2026-08-28T00:00:00Z",
    },
    {
      id: "user-owner",
      name: "Kevin Bhutwala",
      email: "kevinbhutwala417@gmail.com",
      passwordHash: adminPasswordHash,
      role: "agency_admin",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
      verified: true,
      createdAt: "2026-08-30T00:00:00Z",
      updatedAt: "2026-08-31T00:00:00Z",
    },
    {
      id: "user-admin",
      name: "Collably Operations Admin",
      email: "admin@collably.io",
      passwordHash: adminPasswordHash,
      role: "agency_admin",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
      verified: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2026-08-28T00:00:00Z",
    },
  ];

  const now = new Date().toISOString();
  const futureDate = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();

  const initialSubscriptions: SubscriptionEntity[] = [
    // Creator Pro
    {
      id: "sub-c1",
      userId: "user-c1",
      role: "creator",
      planId: "creator_pro",
      status: "active",
      interval: "monthly",
      currentPeriodStart: now,
      currentPeriodEnd: futureDate,
      cancelAtPeriodEnd: false,
      price: 29,
      currency: "USD",
      features: { ...ALL_PLANS.creator_pro.features },
      usage: {
        activeCampaignsCount: 0,
        applicationsThisMonth: 8,
        crmContactsCount: 0,
        aiTokensUsed: 1250,
        lastResetDate: now,
      },
      createdAt: now,
      updatedAt: now,
    },
    // Creator Starter
    {
      id: "sub-c2",
      userId: "user-c2",
      role: "creator",
      planId: "creator_starter",
      status: "active",
      interval: "monthly",
      currentPeriodStart: now,
      currentPeriodEnd: futureDate,
      cancelAtPeriodEnd: false,
      price: 0,
      currency: "USD",
      features: { ...ALL_PLANS.creator_starter.features },
      usage: {
        activeCampaignsCount: 0,
        applicationsThisMonth: 3,
        crmContactsCount: 0,
        aiTokensUsed: 0,
        lastResetDate: now,
      },
      createdAt: now,
      updatedAt: now,
    },
    // Creator Starter Test Account
    {
      id: "sub-c-starter",
      userId: "user-c-starter",
      role: "creator",
      planId: "creator_starter",
      status: "active",
      interval: "monthly",
      currentPeriodStart: now,
      currentPeriodEnd: futureDate,
      cancelAtPeriodEnd: false,
      price: 0,
      currency: "USD",
      features: { ...ALL_PLANS.creator_starter.features },
      usage: {
        activeCampaignsCount: 0,
        applicationsThisMonth: 1,
        crmContactsCount: 0,
        aiTokensUsed: 0,
        lastResetDate: now,
      },
      createdAt: now,
      updatedAt: now,
    },
    // Creator Pro Test Account
    {
      id: "sub-c-pro",
      userId: "user-c-pro",
      role: "creator",
      planId: "creator_pro",
      status: "active",
      interval: "monthly",
      currentPeriodStart: now,
      currentPeriodEnd: futureDate,
      cancelAtPeriodEnd: false,
      price: 29,
      currency: "USD",
      features: { ...ALL_PLANS.creator_pro.features },
      usage: {
        activeCampaignsCount: 0,
        applicationsThisMonth: 4,
        crmContactsCount: 0,
        aiTokensUsed: 300,
        lastResetDate: now,
      },
      createdAt: now,
      updatedAt: now,
    },
    // Creator Enterprise Test Account
    {
      id: "sub-c-ent",
      userId: "user-c-ent",
      role: "creator",
      planId: "creator_enterprise",
      status: "active",
      interval: "annual",
      currentPeriodStart: now,
      currentPeriodEnd: futureDate,
      cancelAtPeriodEnd: false,
      price: 948,
      currency: "USD",
      features: { ...ALL_PLANS.creator_enterprise.features },
      usage: {
        activeCampaignsCount: 0,
        applicationsThisMonth: 12,
        crmContactsCount: 0,
        aiTokensUsed: 4500,
        lastResetDate: now,
      },
      createdAt: now,
      updatedAt: now,
    },
    // Brand Growth
    {
      id: "sub-b1",
      userId: "user-b1",
      role: "brand",
      planId: "brand_growth",
      status: "active",
      interval: "monthly",
      currentPeriodStart: now,
      currentPeriodEnd: futureDate,
      cancelAtPeriodEnd: false,
      price: 199,
      currency: "USD",
      features: { ...ALL_PLANS.brand_growth.features },
      usage: {
        activeCampaignsCount: 3,
        applicationsThisMonth: 0,
        crmContactsCount: 2,
        aiTokensUsed: 800,
        lastResetDate: now,
      },
      createdAt: now,
      updatedAt: now,
    },
    // Brand Starter Test Account
    {
      id: "sub-b-starter",
      userId: "user-b-starter",
      role: "brand",
      planId: "brand_starter",
      status: "active",
      interval: "monthly",
      currentPeriodStart: now,
      currentPeriodEnd: futureDate,
      cancelAtPeriodEnd: false,
      price: 49,
      currency: "USD",
      features: { ...ALL_PLANS.brand_starter.features },
      usage: {
        activeCampaignsCount: 1,
        applicationsThisMonth: 0,
        crmContactsCount: 0,
        aiTokensUsed: 0,
        lastResetDate: now,
      },
      createdAt: now,
      updatedAt: now,
    },
    // Brand Growth Test Account
    {
      id: "sub-b-growth",
      userId: "user-b-growth",
      role: "brand",
      planId: "brand_growth",
      status: "active",
      interval: "monthly",
      currentPeriodStart: now,
      currentPeriodEnd: futureDate,
      cancelAtPeriodEnd: false,
      price: 199,
      currency: "USD",
      features: { ...ALL_PLANS.brand_growth.features },
      usage: {
        activeCampaignsCount: 4,
        applicationsThisMonth: 0,
        crmContactsCount: 15,
        aiTokensUsed: 1200,
        lastResetDate: now,
      },
      createdAt: now,
      updatedAt: now,
    },
    // Brand Enterprise Test Account
    {
      id: "sub-b-ent",
      userId: "user-b-ent",
      role: "brand",
      planId: "brand_enterprise",
      status: "active",
      interval: "annual",
      currentPeriodStart: now,
      currentPeriodEnd: futureDate,
      cancelAtPeriodEnd: false,
      price: 5988,
      currency: "USD",
      features: { ...ALL_PLANS.brand_enterprise.features },
      usage: {
        activeCampaignsCount: 14,
        applicationsThisMonth: 0,
        crmContactsCount: 120,
        aiTokensUsed: 8900,
        lastResetDate: now,
      },
      createdAt: now,
      updatedAt: now,
    },
    // Admin Override Subscriptions
    {
      id: "sub-admin",
      userId: "user-admin",
      role: "agency_admin",
      planId: "brand_enterprise",
      status: "active",
      interval: "annual",
      currentPeriodStart: now,
      currentPeriodEnd: futureDate,
      cancelAtPeriodEnd: false,
      price: 0,
      currency: "USD",
      features: {
        ...ALL_PLANS.brand_enterprise.features,
        adminOverride: true,
        maxActiveCampaigns: -1,
        maxApplicationsPerMonth: -1,
        aiPitchGenerator: true,
        advancedAnalytics: true,
        instantPayouts: true,
        verifiedBadge: true,
      },
      usage: {
        activeCampaignsCount: 0,
        applicationsThisMonth: 0,
        crmContactsCount: 0,
        aiTokensUsed: 0,
        lastResetDate: now,
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "sub-owner",
      userId: "user-owner",
      role: "agency_admin",
      planId: "brand_enterprise",
      status: "active",
      interval: "annual",
      currentPeriodStart: now,
      currentPeriodEnd: futureDate,
      cancelAtPeriodEnd: false,
      price: 0,
      currency: "USD",
      features: {
        ...ALL_PLANS.brand_enterprise.features,
        adminOverride: true,
        maxActiveCampaigns: -1,
        maxApplicationsPerMonth: -1,
        aiPitchGenerator: true,
        advancedAnalytics: true,
        instantPayouts: true,
        verifiedBadge: true,
      },
      usage: {
        activeCampaignsCount: 0,
        applicationsThisMonth: 0,
        crmContactsCount: 0,
        aiTokensUsed: 0,
        lastResetDate: now,
      },
      createdAt: now,
      updatedAt: now,
    },
  ];

  return {
    users: initialUsers,
    creators: [...MOCK_CREATORS],
    brands: [...MOCK_BRANDS],
    campaigns: [...MOCK_CAMPAIGNS],
    applications: [
      {
        id: "app-1",
        campaignId: "camp-1",
        campaignTitle: "AI-Powered Sprint Workflows Launch",
        brandId: "brand-1",
        brandName: "Linear Dynamics",
        brandLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80",
        creatorId: "creator-1",
        creator: MOCK_CREATORS[0],
        status: "accepted",
        pitch: "I'd love to produce an in-depth 60s integration showcasing how Linear AI triages complex sprint backlogs in our daily 4-person dev team.",
        proposedFee: 3500,
        estimatedReach: 240000,
        sampleLinks: ["https://youtube.com/@elenatech/videos"],
        matchScore: 94,
        createdAt: "2026-08-25T14:30:00Z",
        updatedAt: "2026-08-25T14:30:00Z",
      },
    ],
    collaborations: [...MOCK_COLLABORATIONS],
    payouts: [
      {
        id: "pay-1",
        creatorId: "creator-1",
        campaignId: "camp-1",
        collaborationId: "collab-1",
        campaignTitle: "AI-Powered Sprint Workflows Launch",
        brandName: "Linear Dynamics",
        creatorName: "Elena Rostova",
        deliverableTitle: "YouTube 60s Integration",
        grossAmount: 3500,
        agencyFee: 350,
        netAmount: 3150,
        status: "processing",
        paymentMethod: "Stripe Direct",
        createdAt: "2026-08-28T16:50:00Z",
      },
      {
        id: "pay-2",
        creatorId: "creator-2",
        campaignId: "camp-2",
        collaborationId: "collab-2",
        campaignTitle: "The Architecture of Time",
        brandName: "Aethel Watches",
        creatorName: "Marcus Vance",
        deliverableTitle: "Instagram Reel",
        grossAmount: 2000,
        agencyFee: 200,
        netAmount: 1800,
        status: "paid",
        paymentMethod: "Wire Transfer",
        createdAt: "2026-08-26T12:15:00Z",
        releasedAt: "2026-08-27T09:00:00Z",
      },
    ],
    subscriptions: initialSubscriptions,
    crmContacts: [
      {
        id: "crm-1",
        creatorId: "creator-1",
        creator: MOCK_CREATORS[0],
        brandId: "brand-1",
        stage: "Active_Partner",
        tags: ["AI", "DeveloperTools", "HighEngagement", "Tier1"],
        privateNotes: [
          {
            id: "note-1",
            authorName: "Sarah (Growth Lead)",
            content: "Elena had outstanding 6.4% engagement on the Sprint AI launch. High conversion to free trials.",
            createdAt: "2026-08-20",
          },
        ],
        pastCampaignsCount: 3,
        totalPaid: 10500,
        lastContactedAt: "2026-08-28",
      },
      {
        id: "crm-2",
        creatorId: "creator-2",
        creator: MOCK_CREATORS[1] || MOCK_CREATORS[0],
        brandId: "brand-1",
        stage: "Outreach",
        tags: ["Minimalist", "Architecture", "Luxury"],
        privateNotes: [
          {
            id: "note-2",
            authorName: "Alex (Creative Director)",
            content: "Reaching out for Q4 hardware campaign. Fits dark aesthetic.",
            createdAt: "2026-08-25",
          },
        ],
        pastCampaignsCount: 1,
        totalPaid: 2800,
        lastContactedAt: "2026-08-26",
      },
    ],
    shortlists: [
      {
        id: "sl-1",
        brandId: "brand-1",
        name: "Q4 Developer Ecosystem Launch",
        description: "Top AI engineers and technical reviewers for our 2.0 release.",
        creatorIds: ["creator-1", "creator-4"],
        creators: [MOCK_CREATORS[0], MOCK_CREATORS[3] || MOCK_CREATORS[0]],
        createdAt: "2026-08-10",
        updatedAt: "2026-08-28",
      },
    ],
    disputes: [
      {
        id: "disp-1",
        collaborationId: "collab-2",
        campaignTitle: "The Architecture of Time: Autumn Collection",
        brandName: "Aethel Watches",
        creatorName: "Marcus Vance",
        reason: "Missed_Deadline",
        description: "Final 4K reel deliverable was submitted 4 days past the agreed deadline without prior notice.",
        amountInDispute: 2800,
        filedBy: "brand",
        status: "Evidence_Submitted",
        evidenceLinks: ["https://vimeo.com/preview/draft-late"],
        adminArbitrationNotes: "Creator was in transit for location shoot. Resolution proposed: 10% late penalty with full release of balance.",
        createdAt: "2026-08-26",
      },
    ],
    tickets: [
      {
        id: "tkt-1",
        userId: "user-c1",
        userName: "Elena Rostova",
        userRole: "creator",
        subject: "Stripe Connect payout tax document question",
        category: "Billing",
        priority: "Medium",
        status: "In_Progress",
        messages: [
          {
            id: "m-1",
            senderName: "Elena Rostova",
            senderRole: "creator",
            content: "Hi team, I need to update my European VAT ID on the platform ledger.",
            createdAt: "2026-08-28 10:15",
          },
        ],
        createdAt: "2026-08-28",
        updatedAt: "2026-08-28",
      },
    ],
    payments: [],
    mediaAssets: [],
    conversations: [...MOCK_CONVERSATIONS],
    messages: Object.values(MOCK_MESSAGES).flat(),
    notifications: [],
    webhookEvents: [],
    aiUsage: [],
    auditLogs: [
      {
        id: "aud-1",
        actorId: "user-b1",
        actorName: "Linear Dynamics",
        actorRole: "brand",
        action: "CAMPAIGN_PUBLISHED",
        entityType: "Campaign",
        entityId: "camp-1",
        entityName: "AI-Powered Sprint Workflows Launch",
        metadata: { budget: 45000, maxCreators: 5 },
        ipAddress: "192.168.1.42",
        createdAt: "2026-08-28 14:10:22",
      },
    ],
  };
}
